import { ProcessGraphJson } from './types';

/**
 * Processo comercial ARW — notação alinhada ao BPMN 2.0
 * (Pool, User Task, Service Task, Exclusive Gateway, Start/End Event, Sequence Flow)
 */
export const ARW_COMERCIAL_GRAPH: ProcessGraphJson = {
  version: 1,
  layout: 'LR',
  pool: 'ARW — Processo comercial (B2B)',
  lanes: ['Captação', 'Qualificação', 'Negociação', 'Fechamento', 'Onboarding'],
  nodes: [
    { id: 'Start', kind: 'startEnd', label: 'Lead entra no funil', lane: 'Captação', bpmn: { event: 'start' } },
    { id: 'A', kind: 'activity', phase: 'Captação', label: 'Verificar dados do lead', bpmn: { task: 'userTask' } },
    { id: 'B', kind: 'activity', phase: 'Captação', label: 'Pesquisar empresa (ICP)', bpmn: { task: 'userTask' } },
    { id: 'C', kind: 'activity', phase: 'Captação', label: 'Primeira abordagem (SDR)', bpmn: { task: 'userTask' } },
    { id: 'D', kind: 'decision', label: 'Respondeu?', lane: 'Captação', bpmn: { gateway: 'exclusive' } },
    { id: 'E', kind: 'activity', phase: 'Qualificação', label: 'Qualificar lead (BANT)', bpmn: { task: 'userTask' } },
    {
      id: 'P',
      kind: 'automation',
      phase: 'Captação',
      label: 'Disparar sequência de follow-up',
      bpmn: { task: 'serviceTask' },
    },
    { id: 'F', kind: 'decision', label: 'Qualificado?', lane: 'Qualificação', bpmn: { gateway: 'exclusive' } },
    { id: 'G', kind: 'activity', phase: 'Qualificação', label: 'Agendar reunião com closer', bpmn: { task: 'userTask' } },
    {
      id: 'Q',
      kind: 'automation',
      phase: 'Qualificação',
      label: 'Incluir em campanha de nurturing',
      bpmn: { task: 'serviceTask' },
    },
    { id: 'EndN', kind: 'startEnd', label: 'Fim — lead nutrido', lane: 'Qualificação', bpmn: { event: 'end' } },
    { id: 'H', kind: 'activity', phase: 'Negociação', label: 'Discovery / diagnóstico (Closer)', bpmn: { task: 'userTask' } },
    { id: 'I', kind: 'activity', phase: 'Negociação', label: 'Apresentar solução', bpmn: { task: 'userTask' } },
    { id: 'J', kind: 'activity', phase: 'Negociação', label: 'Enviar proposta comercial', bpmn: { task: 'userTask' } },
    { id: 'K', kind: 'decision', label: 'Proposta aceita?', lane: 'Negociação', bpmn: { gateway: 'exclusive' } },
    { id: 'L', kind: 'automation', phase: 'Fechamento', label: 'Gerar minuta de contrato', bpmn: { task: 'serviceTask' } },
    { id: 'S', kind: 'activity', phase: 'Negociação', label: 'Tratar objeções e negociar', bpmn: { task: 'userTask' } },
    { id: 'M', kind: 'automation', phase: 'Fechamento', label: 'Enviar contrato (assinatura eletrônica)', bpmn: { task: 'serviceTask' } },
    { id: 'N', kind: 'activity', phase: 'Fechamento', label: 'Emitir fatura', bpmn: { task: 'manualTask' } },
    { id: 'O', kind: 'activity', phase: 'Onboarding', label: 'Kickoff com cliente (CS)', bpmn: { task: 'userTask' } },
    { id: 'End', kind: 'startEnd', label: 'Fim — cliente ativo', lane: 'Onboarding', bpmn: { event: 'end' } },
  ],
  edges: [
    { from: 'Start', to: 'A' },
    { from: 'A', to: 'B' },
    { from: 'B', to: 'C' },
    { from: 'C', to: 'D' },
    { from: 'D', to: 'E', label: 'Sim' },
    { from: 'D', to: 'P', label: 'Não' },
    { from: 'P', to: 'C' },
    { from: 'E', to: 'F' },
    { from: 'F', to: 'G', label: 'Sim' },
    { from: 'F', to: 'Q', label: 'Não' },
    { from: 'Q', to: 'EndN' },
    { from: 'G', to: 'H' },
    { from: 'H', to: 'I' },
    { from: 'I', to: 'J' },
    { from: 'J', to: 'K' },
    { from: 'K', to: 'L', label: 'Sim' },
    { from: 'K', to: 'S', label: 'Não' },
    { from: 'S', to: 'J' },
    { from: 'L', to: 'M' },
    { from: 'M', to: 'N' },
    { from: 'N', to: 'O' },
    { from: 'O', to: 'End' },
  ],
};
